import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// In dev, if OBSIDIAN_VAULT points at a vault, build straight into its plugin
// folder and emit a `.hotreload` marker so the Hot Reload plugin reloads us
// on every rebuild. Otherwise (and always in prod) write to the repo root.
const vault = process.env.OBSIDIAN_VAULT;
const outDir = !prod && vault ? path.join(vault, '.obsidian/plugins/obsidian-objects') : '.';
if (outDir !== '.') mkdirSync(outDir, { recursive: true });

// After each build, sync the sidecar release files into the vault and touch
// `.hotreload`. A no-op when building to the repo root.
const hotReloadPlugin = {
  name: 'objects-hot-reload',
  setup(build) {
    build.onEnd(() => {
      if (outDir === '.') return;
      for (const file of ['manifest.json', 'styles.css']) {
        if (existsSync(file)) copyFileSync(file, path.join(outDir, file));
      }
      writeFileSync(path.join(outDir, '.hotreload'), '');
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(outDir, 'main.js'),
  minify: prod,
  plugins: [hotReloadPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
